default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cms_development

test:
  <<: *default
  database: cms_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
  # username: cihangirakinci
  # password: <%= ENV['CMS_DATABASE_PASSWORD'] %>
